
name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  upload:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Create a File
      run: echo "hello from ${{ matrix.runs-on }}" > ci.json
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ci-data #my-artifact-${{ matrix.runs-on }}
        path: ci.json #file-${{ matrix.runs-on }}.txt
  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: my-artifact
        pattern: ci-* #my-artifact-*
        merge-multiple: true
    - run: cat my-artifact/ci.json